### ISSUE TITLE
Sprint 2A Checklist

### ISSUE THREAD

**Issue by ncongjuico** [tpearce01/ICS168#4]
**Unity & Databases (Zach & Ney)**
- [x] 1. Have a database running (phpmyadmin)
- [x] 2. Correctly connect and pull information from that database
- [x] 3. Create a script that pushes new accounts into database
- [x] 4. Correctly match and verify login and password
- [x] 5. User authentication, make sure username doesn't already exist in database

**Networking & Controls (Daniel & Tyler)**
- [x] 1. Prepare Server-Client system for multiplayer mode
- [x] 2. Screenshots technique to send rendered screens (JSON or Marshalling?)
- [x]    - Game state snapshots
- [x]    - Time stamps for latency mitigation (probably Sprint 2B)
- [x] 3. Figure out how to do multiple instances to run client/server.
- [ ] 4. Latency mitigation, lockstep with time manipulation (probably Sprint 2B)
  - changed, will probably do something else
- [x] 5. Migrate game logic to server (probably Sprint 2B)

**Game Features/Aesthetics (Al)**
- [ ] 1. Replace player sprite (optional)
- [x] 2. Replace bomb sprite (Zach)
- [x] 3. Allow destructible walls to drop power-ups
- [x] 4. Randomize destructible wall generation (Ney)
- [ ] 5. Power-ups
- [ ]    - extra bombs (optional)
- [x]    - more powerful bombs
- [x] 6. Sounds
- [ ] 7. Movement (optional)
