### ISSUE TITLE
Sprint 1 Checklist

### ISSUE THREAD

**Issue by ncongjuico** [tpearce01/ICS168#5]
**Things left to do:**

**Game Manager**
- [x]     - Check if there's a winner, if there is, end game
- [x]     - Check if the time limit expired, if it did, end game
- [x]     - Switch scene to Main Menu if game ended
- [x]     - Time Limit
- [x]     - Display who's the victor
- [x]     - Keep track of player’s # of bombs (optional)

**Level Editor**
- [x]     - Translate txt file to level scene
- [x]     - Destructible and Indestructible walls
- [x]     - Spawn Locations

**Bomb**
- [x]     - 1 block explosion
- [x]     - Explosion destroys Destructible Wall
- [x]     - Kills Player if explosion touches player

**Player**
- [x]    - Movement
- [x]     - Place Bomb

**Main Menu**
- [x]     - Play Game -> Game Scene
- [x]     - Controls -> Controls Menu (low priority)
- [x]     - Credits -> Credits Menu (low priority)
- [x]     - Quit Game

**Tyler’s Camera Script (future sprint)**

**HUD**
- [x]     - Which players are alive (optional)
- [x]     - Time Countdown
