### ISSUE TITLE
Sprint 2B Checklist

### ISSUE THREAD

**Issue by ncongjuico** [tpearce01/ICS168#6]
**Integration**
- [x] 1. Combining the Network branch with Database branch
- [ ] 2. Get the sound to work over the network (using Wwise or Sound Manager?)
- [ ] 3. Create devbranch

**Networking**
- [x] 1. Time stamps for latency mitigation
- [x] 2. Get 2+ player controls to work\
- [x] 3. Connecting using different networks (used Port Forwarding on Daniel's end)

**Game Mechanics**
- [x] 1. Spawn players in all 4 corners
- [x] 2. Fix Randomize Wall script (give space to players)
- [ ] 3. If an account is already logged in, disallow any future logins with the same account
- [x] 4. When account is created, display success image and display login button

**Login**
- [x] 1. LoginWindow sends username and password to Server
- [x] 2. Server verifies username and password with database and sends back a message to client (valid, invalid, user not found)
- [x] 3. If invalid/user not found, display error message
- [x] 4. If valid, start streaming lobby from server

**Create Account**
- [x] 1. NewAccountWindow sends username and password to Server
- [x]    - checks if passwords match before sending it off to server
- [x] 2. Server tries to create account with database and sends back message to client (username exists, account created)
- [x] 3. If username exists, display error message
- [x] 4. If account created, toggle NewAccount window to NewAccountSuccess window

**Optional list**
- [ ] 1. Replace player sprite
- [ ] 2. Power-ups
- [ ]  - extra bombs
- [ ]  - time bomb
- [ ]  - molotov bomb
- [ ] 3. Smoothing out movement
