### ISSUE TITLE
Sprint 4 Checklist (due May 30, Tuesday)

### ISSUE THREAD

**Issue by ncongjuico** [tpearce01/ICS168#9]
**Game Mechanics:**
- [x] Allow players to join in when a game has already started (or a diff method of doing this)
- [x] Destroy player object when a player disconnects
- [x] Show an indication that a player joined or left the game sessions (possibly just a chat dialogue box)
- [x] Deliverable: A demo consisting of 2 game sessions. Each session has 2 game clients (a total of 4 game clients in 2 sessions) connected to it. Each session has a different game instance.

**Windows:**
- [x] Have a persistent lobby with the game window that shows when a player enters or leaves (can have it so it tells the client it can join the next game when a current game is in progress)

**Sessions:**
- [x] Research ways to do game sessions that work with our streaming algorithm
- multiple game instances using different ports to connect to the server?
- different games running in the same scene with different cameras attached to each (would require multiple game and window managers)
- [x] In login window, additional text box for a session name (might need to change)
- [x] If session name does not exist, create that session (might need to change)
- [x] If session exists, join the session (might need to change)
- [x] If text box is empty, join a default session (might need to change)

**--------Current bug list--------**
**Client-Server/Network bugs:**
~~Client is processing at a slower speed than the Server~~
- [x] Make sure server only sends messages to clients who need it (ex. send "Disable Cancel" on client window for people in the lobby)
- [x] If the client continually searches for the server, an error appears
- [x] If a client disconnects while logging in, it sets that player to a different connectionID when it connects again, but it can't control its player (with the assigned color) because it's linked to the previous connectionID 
- [x] White screen bug, if a client leaves an instance and rejoins it, it displays a white screen

**Player bugs:**
- [x] When a game starts up again, old players can't move (only new players can)
- [x] When a player dies, top-right tile turns white for some reason

**Window bugs:**
- [x] Controls Window blocks Back to Main button
- [ ] On Controls and Credits window, it automatically redirects player to Start window without clicking on any of the buttons
- [x] Login Window sometimes doesn't let the player login when clicking the login button --- usually happens when the player finishes a previous game and needs to login again
- [x] Game doesn't check for an account that is already logged in
- [x] When game ends, game server redirects clients to GameSelect window but "Join Game" is still greyed out.
- [x] If player clicks "Back to Main" while in the GameSelect window, and they try to login again with the same username and password, it prevents them from logging in. (Solution: Whenever a client clicks "back to main," set them as logged out).
- [x] Persistent lobby doesn't show up

**Milestone 5 List:**
- [x] 1. If the game is in session and a player leaves the game should delete the player and do all necessary clean up.
     * THIS IS A MAJOR ISSUE.
- [x] 2. If a Game Server instance is at capactiy, do not allow any more players to connect.
- [x]     2a. Provide message why they cannot connect.
- [x] 3. Verify that all "warning" messages are working properly. Ex. Bad Logins.
- [x] 4. When a game is being created, display a message on why they are not currently connected.
- [x]     4a. Possibly deactivate the button so they don't try and connect twice. (Decide if this is necessary or not if there is a message.)
- [x] 5. After the lobby states the game is about to start and the cancel from game button is greyed out, prevent any more connections to that server instance. (If the game is about to be or is in session, no more players can connect.)
- [x] 6. Finish implementing the "persistent" lobby.
- [x] 7. Ensure that two or more people are not logged on to the same account at any given time.
- [x] 8. Re-color destructible walls to distinguish between the two.
- [x] 9. Ensure the Master Server does not create more game instances than the limit.
- [x] 10. Update the current number of active game instances. (There is a variable already there, just needs to be updated).

**Comment by ncongjuico** [comment]
**What we did: (for Sprint Report)**
Player Encapsulation
Game session matchmaking (see commits on 5/24/17)
Optimized deltas to work with colors
Worked on notification area (for ziv's lobby request), currently under construction
Updated fonts to blocky font to work with Tyler's deltas

**After final demo:**
GREAT WORK TEAM!!!! :D Proud of this awesome group of people!
